apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: contactform-rootpass   # base64 encoded
  MYSQL_USER: contactformdb-admin             # base64 encoded
  MYSQL_PASSWORD: contactform-password        # base64 encoded