pipeline {
    agent any
    stages {
        stage('build_image') {
            steps {
                script {
                    echo "Building Docker Image..."
                    sh 'docker build -t oluwaseuna/demo-app:nodeapp .'
                }
            }
        }
        stage('build') {
            steps {
                script {
                    echo "Build Docker Image with Dockerfile..."
                    gv.buildImage()
                }
            }
        }
        stage('push') {
            steps {
                script {
                    echo "Pushing Docker Image to Docker Hub Repo..."
                    gv.pushImage()
                }
            }
        }
        stage('deploy') {
            steps {
                script {
                    echo "Deploying the application to EC2..."
                    gv.deployImage()
                }
            }
        }
    }   
}